"""
Ingest the North America Real Estate Tracker XLSX into a static JS module
consumed by src/data/realEstateMarkets.js at build/runtime.

Usage:
    python3 scripts/ingestMarkets.py <path/to/tracker.xlsx> <path/to/output.js>

Reads the History sheet, keeps the most recent snapshot per market_name,
enriches missing metadata from the Reference sheet, and writes a plain
JavaScript array with a small set of helper functions. Prices are kept
in both native currency (for display) and USD (for cross-country compare).
"""
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path

import openpyxl


def slug(name: str) -> str:
    """'New York, NY' -> 'new-york-ny'"""
    s = name.lower().strip()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')


def iso_date(value) -> str | None:
    if value is None:
        return None
    if isinstance(value, (datetime, date)):
        return value.date().isoformat() if isinstance(value, datetime) else value.isoformat()
    return str(value)


def as_number(value):
    if value is None or value == '':
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def read_reference(ws):
    """Return {market_name: {country, region, state, population, densityTier}}."""
    header = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
    idx = {h: i for i, h in enumerate(header)}
    out = {}
    for r in range(2, ws.max_row + 1):
        row = [ws.cell(r, c).value for c in range(1, ws.max_column + 1)]
        name = row[idx['market_name']]
        if not name:
            continue
        out[name] = {
            'country': row[idx['country']],
            'region': row[idx['region']],
            'state': row[idx['state_or_province']],
            'population': as_number(row[idx['population']]),
            'densityTier': row[idx['density_tier']],
        }
    return out


def read_history(ws, reference):
    """Return one dict per unique market_name with the latest snapshot."""
    header = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
    idx = {h: i for i, h in enumerate(header)}
    latest = {}  # market_name -> row dict
    for r in range(2, ws.max_row + 1):
        row = [ws.cell(r, c).value for c in range(1, ws.max_column + 1)]
        name = row[idx['market_name']]
        snap = row[idx['snapshot_month']]
        if not name or snap is None:
            continue
        existing = latest.get(name)
        if existing is None or snap > existing['_snap']:
            latest[name] = {
                '_snap': snap,
                'name': name,
                'country': row[idx['country']],
                'region': row[idx['region']],
                'state': row[idx['state_or_province']],
                'population': as_number(row[idx['population']]),
                'densityTier': row[idx['density_tier']],
                'currency': row[idx['currency']],
                'medianPrice': as_number(row[idx['price']]),
                'medianPriceUsd': as_number(row[idx['price_usd']]),
                'medianRent': as_number(row[idx['rent']]),
                'medianRentUsd': as_number(row[idx['rent_usd']]),
                'priceToRentRatio': as_number(row[idx['price_to_rent_ratio']]),
                'priceSource': row[idx['price_source']],
                'priceDate': iso_date(row[idx['price_date']]),
            }

    # Fill any missing metadata from the Reference sheet.
    for name, m in latest.items():
        ref = reference.get(name) or {}
        for k in ('country', 'region', 'state', 'population', 'densityTier'):
            if m.get(k) in (None, '') and ref.get(k) not in (None, ''):
                m[k] = ref[k]

    return latest


def to_js(markets, snapshot_summary):
    """Emit a readable JS module."""
    header = f"""// AUTO-GENERATED by scripts/ingestMarkets.py
// Source: North America Residential Real Estate Tracker.xlsx
// Snapshot: {snapshot_summary}
// Markets: {len(markets)}
//
// Do not edit by hand. To refresh, run:
//   python3 scripts/ingestMarkets.py <path-to-xlsx> src/data/realEstateMarkets.js

"""
    lines = ['export const MARKETS = [']
    for m in markets:
        # Emit an object literal with fields in a consistent order.
        pieces = [
            f"    id: {json.dumps(m['id'])},",
            f"    name: {json.dumps(m['name'])},",
            f"    country: {json.dumps(m['country'])},",
            f"    state: {json.dumps(m['state'])},",
            f"    region: {json.dumps(m['region'])},",
            f"    population: {int(m['population']) if m.get('population') is not None else 'null'},",
            f"    densityTier: {json.dumps(m['densityTier'])},",
            f"    currency: {json.dumps(m['currency'])},",
            f"    medianPrice: {int(round(m['medianPrice'])) if m.get('medianPrice') is not None else 'null'},",
            f"    medianPriceUsd: {int(round(m['medianPriceUsd'])) if m.get('medianPriceUsd') is not None else 'null'},",
            f"    medianRent: {int(round(m['medianRent'])) if m.get('medianRent') is not None else 'null'},",
            f"    medianRentUsd: {int(round(m['medianRentUsd'])) if m.get('medianRentUsd') is not None else 'null'},",
            f"    priceToRentRatio: {m.get('priceToRentRatio') if m.get('priceToRentRatio') is not None else 'null'},",
            f"    priceSource: {json.dumps(m['priceSource'])},",
            f"    priceDate: {json.dumps(m['priceDate'])},",
        ]
        lines.append('  {')
        lines.extend(pieces)
        lines.append('  },')
    lines.append(']')
    body = '\n'.join(lines)

    helpers = """

// Fast id -> market lookup, built once at module load.
const BY_ID = new Map(MARKETS.map((m) => [m.id, m]))

/** Look up a market by its slug id. Returns null when not found. */
export function findMarket(id) {
  if (!id) return null
  return BY_ID.get(id) || null
}

/**
 * Prefix / substring search across the market's display name, state, and
 * region. Returns up to `limit` matches. Empty query returns the first N
 * markets (useful for a "browse" mode in the picker).
 */
export function searchMarkets(query, limit = 8) {
  if (!query) return MARKETS.slice(0, limit)
  const q = String(query).toLowerCase().trim()
  if (!q) return MARKETS.slice(0, limit)
  const hits = []
  for (const m of MARKETS) {
    const hay = `${m.name} ${m.state || ''} ${m.region || ''}`.toLowerCase()
    if (hay.includes(q)) hits.push(m)
    if (hits.length >= limit) break
  }
  return hits
}

/**
 * Filter markets by country and/or region. Pass null/undefined to skip
 * either filter. Preserves the source ordering.
 */
export function marketsByRegion(country, region) {
  return MARKETS.filter((m) =>
    (!country || m.country === country) &&
    (!region  || m.region  === region),
  )
}
"""
    return header + body + helpers


def main():
    if len(sys.argv) < 3:
        print('Usage: ingestMarkets.py <xlsx> <out.js>', file=sys.stderr)
        sys.exit(2)
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])

    wb = openpyxl.load_workbook(src, data_only=True)
    reference = read_reference(wb['Reference'])
    latest = read_history(wb['History'], reference)

    # Sort markets: US then CA, then alphabetical within each country.
    markets = []
    for name in sorted(latest.keys()):
        m = latest[name]
        markets.append({
            'id': slug(name),
            'name': m['name'],
            'country': m['country'],
            'state': m['state'],
            'region': m['region'],
            'population': m['population'],
            'densityTier': m['densityTier'],
            'currency': m['currency'],
            'medianPrice': m['medianPrice'],
            'medianPriceUsd': m['medianPriceUsd'],
            'medianRent': m['medianRent'],
            'medianRentUsd': m['medianRentUsd'],
            'priceToRentRatio': m['priceToRentRatio'],
            'priceSource': m['priceSource'],
            'priceDate': m['priceDate'],
        })
    markets.sort(key=lambda m: (0 if m['country'] == 'US' else 1, m['name']))

    snap_dates = sorted({m['_snap'] for m in latest.values()})
    snapshot_summary = (
        f"{snap_dates[0].date().isoformat()}..{snap_dates[-1].date().isoformat()}"
        if snap_dates else 'unknown'
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(to_js(markets, snapshot_summary), encoding='utf-8')
    print(f'Wrote {len(markets)} markets to {out}')


if __name__ == '__main__':
    main()
