import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import { useAuth } from './AuthContext.jsx'

const PlannerContext = createContext(null)

const PROFILES_KEY = 'beanstalk.profiles'

const emptyProfile = {
  completedWizard: false,
  personal: {
    fullName: '',
    // Birth date drives age-anchored forecasts. We keep both pieces as
    // strings for controlled-input consistency; helpers in utils/age
    // derive the live age. `age` stays as a legacy fallback for profiles
    // that haven't migrated yet.
    birthMonth: '', // '1'..'12'
    birthYear: '',  // four-digit year, e.g. '1992'
    age: '',        // legacy — used only if birth date isn't set
    lifeStage: [], // multi-select — array of stage labels
    country: '',   // 'CA' | 'US'
    region: '',    // province (CA) or state (US)
  },
  goals: [], // { id, title, category, targetAge, ... }
  priorities: [], // ordered list of goal ids
  assets: [], // { id, label, amount, subtype, monthlyPayment, note?,
              //   customRate?,        // per-asset rate override (stockOptions ROI)
              //   retirementAge?,     // pension: age annuity begins
              //   annualAnnuity?,     // pension: forecasted annual annuity
              // }
  liabilities: [], // { id, label, amount, note? }
  // Action plan checklist generated by the gameboard. Survives navigation
  // so the user can tick off real-world steps from anywhere in the app.
  actionPlan: [], // { id, kind, emoji, title, detail, month, done }
  snapshotSeeded: false, // true once we've seeded assets/liabilities from wizard finances
  finances: {
    monthlyIncome: '', // after-tax take-home — total, summed from sources
    incomeSources: {  // per-source breakdown set via the Play page Income modal
      employment: '',
      selfEmployment: '',
      business: '',
    },
    monthlyExpenses: '',
    bareNecessities: '', // fixed monthly expenditures (rent, utilities, etc.)
    // Self-assessment of how content the user is with their discretionary
    // spending power. Set by the BuyingPowerModal on the Money page.
    // Shape: { ratings: {key: 0-10}, avg, content: boolean, assessedAt: ISO }
    buyingPowerAssessment: null,
    liquidAssets: '',
    investments: '',
    realEstate: '',
    debts: '',
    riskTolerance: '', // low | medium | high
    savingsRate: '',
  },
  // Typical return / interest rates applied per type. Values are percentages
  // stored as strings (so the inputs stay controlled); Number() them at read time.
  rates: {
    asset: {
      savings: '',
      retirement: '',
      investments: '',
      realEstate: '',
      crypto: '',
    },
    liability: {
      creditCard: '',
      lineOfCredit: '',
      overdueBills: '',
      carLoan: '',
      mortgage: '',
    },
  },
  preferences: {
    focusArea: '', // money | career | health | relationships | learning
  },
  // Cozy Play-section state — see IMMERSIVE_GAMEPLAY.md. `items` holds
  // everything unlocked; `placed` distinguishes room décor from inventory.
  room: {
    // baselineNetWorth/updatedAt anchor the season comparison in utils/room.js
    // — season only re-checks every few days so it doesn't flap on daily noise.
    season: { current: 'spring', source: 'auto', updatedAt: null, baselineNetWorth: null },
    carePoints: 0,
    streak: { current: 0, longest: 0, lastVisitDate: null }, // lastVisitDate: 'YYYY-MM-DD'
    items: [], // { id, kind: 'plant'|'decor'|'pet'|'food', speciesId, sourceGoalId?,
               //   unlockedAt, placed, slotId, lastTendedAt }
    // What's already been granted, so utils/room.js#unlocksFromMilestones can
    // detect *new* milestones without re-granting the same one twice.
    milestones: { goalIds: [], wealthLevel: -1, petStreak: 0 },
    settings: {
      reducedMotion: 'system', // 'system' | 'on' | 'off'
    },
  },
}

function readProfiles() {
  try {
    return JSON.parse(localStorage.getItem(PROFILES_KEY) || '{}')
  } catch {
    return {}
  }
}
function writeProfiles(map) {
  localStorage.setItem(PROFILES_KEY, JSON.stringify(map))
}

export function PlannerProvider({ children }) {
  const { user } = useAuth()
  const [profile, setProfile] = useState(null)

  // Load the profile tied to the current user
  useEffect(() => {
    if (!user) {
      setProfile(null)
      return
    }
    const all = readProfiles()
    const saved = all[user.id]
    // Shallow-merge over emptyProfile so top-level sections added after a
    // profile was first saved (e.g. `room`) backfill instead of being
    // undefined for existing users.
    setProfile(saved ? { ...emptyProfile, ...saved } : { ...emptyProfile })
  }, [user])

  // Persist whenever the profile changes
  useEffect(() => {
    if (!user || !profile) return
    const all = readProfiles()
    all[user.id] = profile
    writeProfiles(all)
  }, [user, profile])

  const updateProfile = useCallback((patchOrFn) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const patch = typeof patchOrFn === 'function' ? patchOrFn(base) : patchOrFn
      return { ...base, ...patch }
    })
  }, [])

  const updateSection = useCallback((section, patch) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      return { ...base, [section]: { ...base[section], ...patch } }
    })
  }, [])

  const setGoals = useCallback((goals) => {
    setProfile((prev) => ({ ...(prev || emptyProfile), goals }))
  }, [])

  const setPriorities = useCallback((priorities) => {
    setProfile((prev) => ({ ...(prev || emptyProfile), priorities }))
  }, [])

  const addGoal = useCallback((goal) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const next = { id: crypto.randomUUID(), ...goal }
      return {
        ...base,
        goals: [...base.goals, next],
        priorities: [...(base.priorities || []), next.id],
      }
    })
  }, [])

  const removeGoal = useCallback((id) => {
    setProfile((prev) => {
      if (!prev) return prev
      return {
        ...prev,
        goals: prev.goals.filter((g) => g.id !== id),
        priorities: (prev.priorities || []).filter((x) => x !== id),
      }
    })
  }, [])

  const updateGoal = useCallback((id, patch) => {
    setProfile((prev) => {
      if (!prev) return prev
      return {
        ...prev,
        goals: (prev.goals || []).map((g) => (g.id === id ? { ...g, ...patch } : g)),
      }
    })
  }, [])

  const addAsset = useCallback((asset) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      return {
        ...base,
        assets: [...(base.assets || []), { id: crypto.randomUUID(), ...asset }],
      }
    })
  }, [])

  const removeAsset = useCallback((id) => {
    setProfile((prev) => {
      if (!prev) return prev
      return { ...prev, assets: (prev.assets || []).filter((a) => a.id !== id) }
    })
  }, [])

  const updateAsset = useCallback((id, patch) => {
    setProfile((prev) => {
      if (!prev) return prev
      return {
        ...prev,
        assets: (prev.assets || []).map((a) => (a.id === id ? { ...a, ...patch } : a)),
      }
    })
  }, [])

  const addLiability = useCallback((liability) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      return {
        ...base,
        liabilities: [...(base.liabilities || []), { id: crypto.randomUUID(), ...liability }],
      }
    })
  }, [])

  const removeLiability = useCallback((id) => {
    setProfile((prev) => {
      if (!prev) return prev
      return { ...prev, liabilities: (prev.liabilities || []).filter((l) => l.id !== id) }
    })
  }, [])

  const updateLiability = useCallback((id, patch) => {
    setProfile((prev) => {
      if (!prev) return prev
      return {
        ...prev,
        liabilities: (prev.liabilities || []).map((l) => (l.id === id ? { ...l, ...patch } : l)),
      }
    })
  }, [])

  // Rates: update a single rate (scope = 'asset' | 'liability', key = type id)
  const updateRate = useCallback((scope, key, value) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const currentRates = base.rates || emptyProfile.rates
      return {
        ...base,
        rates: {
          ...currentRates,
          [scope]: {
            ...(currentRates[scope] || {}),
            [key]: value,
          },
        },
      }
    })
  }, [])

  // ── Room (cozy Play view) ─────────────────────────────────────────────
  // Advances the visit streak once per calendar day. A gap of more than a
  // day resets rather than escalating a "penalty" — neglect here is meant
  // to be gentle, never a game-over state.
  const recordVisit = useCallback(() => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const room = base.room || emptyProfile.room
      const today = new Date().toISOString().slice(0, 10)
      const last = room.streak?.lastVisitDate
      if (last === today) return base // already recorded today
      const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10)
      const current = last === yesterday ? (room.streak?.current || 0) + 1 : 1
      const longest = Math.max(current, room.streak?.longest || 0)
      return {
        ...base,
        room: { ...room, streak: { current, longest, lastVisitDate: today } },
      }
    })
  }, [])

  // Tending resets an item's decay clock. Visual "care level" is derived
  // from lastTendedAt at read time (utils/room.js) rather than stored, so
  // it can't drift out of sync with the clock that actually drives it.
  const tendItem = useCallback((id) => {
    setProfile((prev) => {
      if (!prev) return prev
      const room = prev.room || emptyProfile.room
      return {
        ...prev,
        room: {
          ...room,
          items: (room.items || []).map((it) =>
            it.id === id ? { ...it, lastTendedAt: new Date().toISOString() } : it,
          ),
        },
      }
    })
  }, [])

  // Unlock a new plant/decor/pet/food item into inventory (unplaced). Goal-
  // or streak-triggered unlocks are minted here; spending care points to
  // place them is the separate micro-economy step (buyRoomItem).
  const unlockRoomItem = useCallback((item) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const room = base.room || emptyProfile.room
      const now = new Date().toISOString()
      const next = {
        id: crypto.randomUUID(),
        placed: false,
        slotId: null,
        unlockedAt: now,
        lastTendedAt: now,
        ...item,
      }
      return { ...base, room: { ...room, items: [...(room.items || []), next] } }
    })
  }, [])

  // Spend care points to place (or rearrange) an owned item. Cost comes
  // from the room catalog at call time, not stored on the item, so prices
  // can be tuned later without migrating saved profiles. A no-op (silently
  // does nothing) if the balance is too low — callers should disable the
  // buy action first using profile.room.carePoints.
  const buyRoomItem = useCallback((id, cost, slotId) => {
    setProfile((prev) => {
      if (!prev) return prev
      const room = prev.room || emptyProfile.room
      const price = Number(cost) || 0
      if ((room.carePoints || 0) < price) return prev
      return {
        ...prev,
        room: {
          ...room,
          carePoints: room.carePoints - price,
          items: (room.items || []).map((it) =>
            it.id === id ? { ...it, placed: true, slotId } : it,
          ),
        },
      }
    })
  }, [])

  // Put a placed item back into inventory. Nothing unlocked is ever
  // deleted — only ever placed or put away.
  const unplaceRoomItem = useCallback((id) => {
    setProfile((prev) => {
      if (!prev) return prev
      const room = prev.room || emptyProfile.room
      return {
        ...prev,
        room: {
          ...room,
          items: (room.items || []).map((it) =>
            it.id === id ? { ...it, placed: false, slotId: null } : it,
          ),
        },
      }
    })
  }, [])

  const addCarePoints = useCallback((amount) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const room = base.room || emptyProfile.room
      return {
        ...base,
        room: { ...room, carePoints: (room.carePoints || 0) + (Number(amount) || 0) },
      }
    })
  }, [])

  const setReducedMotion = useCallback((mode) => {
    setProfile((prev) => {
      const base = prev || emptyProfile
      const room = base.room || emptyProfile.room
      return { ...base, room: { ...room, settings: { ...room.settings, reducedMotion: mode } } }
    })
  }, [])

  // Seed assets/liabilities from wizard finances once, so the snapshot
  // isn't empty the first time the user visits it.
  const seedFromFinances = useCallback(() => {
    setProfile((prev) => {
      if (!prev || prev.snapshotSeeded) return prev
      const assets = [...(prev.assets || [])]
      const liabilities = [...(prev.liabilities || [])]
      const liquid     = Number(prev.finances?.liquidAssets) || 0
      const inv        = Number(prev.finances?.investments)  || 0
      const realEstate = Number(prev.finances?.realEstate)   || 0
      const debts      = Number(prev.finances?.debts)        || 0
      if (liquid > 0)     assets.push({ id: crypto.randomUUID(), label: 'Liquid savings', amount: liquid,     subtype: 'savings',     note: 'From wizard' })
      if (inv > 0)        assets.push({ id: crypto.randomUUID(), label: 'Investments',    amount: inv,        subtype: 'investments', note: 'From wizard' })
      if (realEstate > 0) assets.push({ id: crypto.randomUUID(), label: 'Real estate',    amount: realEstate, subtype: 'realEstate',  note: 'From wizard' })
      if (debts > 0)      liabilities.push({ id: crypto.randomUUID(), label: 'Debts',     amount: debts,      subtype: 'creditCard',  note: 'From wizard' })
      return { ...prev, assets, liabilities, snapshotSeeded: true }
    })
  }, [])

  const completeWizard = useCallback(() => {
    setProfile((prev) => {
      if (!prev) return prev
      // Seed hexes inline so they're ready the moment the dashboard opens.
      const base = { ...prev, completedWizard: true }
      if (base.snapshotSeeded) return base
      const assets = [...(base.assets || [])]
      const liabilities = [...(base.liabilities || [])]
      const liquid     = Number(base.finances?.liquidAssets) || 0
      const inv        = Number(base.finances?.investments)  || 0
      const realEstate = Number(base.finances?.realEstate)   || 0
      const debts      = Number(base.finances?.debts)        || 0
      if (liquid > 0)     assets.push({ id: crypto.randomUUID(), label: 'Liquid savings', amount: liquid,     subtype: 'savings',     note: 'From wizard' })
      if (inv > 0)        assets.push({ id: crypto.randomUUID(), label: 'Investments',    amount: inv,        subtype: 'investments', note: 'From wizard' })
      if (realEstate > 0) assets.push({ id: crypto.randomUUID(), label: 'Real estate',    amount: realEstate, subtype: 'realEstate',  note: 'From wizard' })
      if (debts > 0)      liabilities.push({ id: crypto.randomUUID(), label: 'Debts',     amount: debts,      subtype: 'creditCard',  note: 'From wizard' })
      return { ...base, assets, liabilities, snapshotSeeded: true }
    })
  }, [])

  const resetProfile = useCallback(() => {
    setProfile({ ...emptyProfile })
  }, [])

  const value = useMemo(
    () => ({
      profile,
      updateProfile,
      updateSection,
      setGoals,
      setPriorities,
      addGoal,
      removeGoal,
      updateGoal,
      addAsset,
      removeAsset,
      updateAsset,
      addLiability,
      removeLiability,
      updateLiability,
      updateRate,
      recordVisit,
      tendItem,
      unlockRoomItem,
      buyRoomItem,
      unplaceRoomItem,
      addCarePoints,
      setReducedMotion,
      seedFromFinances,
      completeWizard,
      resetProfile,
    }),
    [
      profile, updateProfile, updateSection, setGoals, setPriorities,
      addGoal, removeGoal, updateGoal,
      addAsset, removeAsset, updateAsset,
      addLiability, removeLiability, updateLiability,
      updateRate,
      recordVisit, tendItem, unlockRoomItem, buyRoomItem, unplaceRoomItem,
      addCarePoints, setReducedMotion,
      seedFromFinances, completeWizard, resetProfile,
    ],
  )

  return <PlannerContext.Provider value={value}>{children}</PlannerContext.Provider>
}

export function usePlanner() {
  const ctx = useContext(PlannerContext)
  if (!ctx) throw new Error('usePlanner must be used inside PlannerProvider')
  return ctx
}
